version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    volumes:
      - $HOME/mongo_data/flashexDB:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: flashex
      # MONGO_INITDB_ROOT_PASSWORD: flashex
    ports:
      - 27017:27017

  cassandra:
    image: cassandra
    container_name: cassandra
    restart: always
    volumes:
      - $HOME/cassandra_data/flashexDB:/data/db
    ports:
      - 9042:9042
    expose:
      - 9042

  kafka:
    # image: wurstmeister/kafka:2.11-2.0.0
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    restart: on-failure
    volumes:
      - $HOME/kakfa_data/flashexDB:/data/db
    environment:
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      # KAFKA_ZOOKEEPER_USER: kafka
      # KAFKA_ZOOKEEPER_PASSWORD: kafka
      # KAFKA_INTER_BROKER_USER: interuser
      # KAFKA_INTER_BROKER_PASSWORD: interpassword
      # KAFKA_BROKER_USER: user
      # KAFKA_BROKER_PASSWORD: password
      # KAFKA_CERTIFICATE_PASSWORD: certificatePassword123
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092,PLAINTEXT_JSON://127.0.0.1:29092
      # KAFKA_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092,PLAINTEXT_JSON://127.0.0.1:29092 
      KAFKA_CREATE_TOPICS: "jackieChanCommand:1:1,Order:1:1:delete,Batches:1:1:delete,Fleet:1:1:delete,TripItinerary:1:1:delete"
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_JSON:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: on-failure
    # environment:
    #   ZOO_ENABLE_AUTH: "yes"
    #   ZOO_SERVER_USERS: flashex
    #   ZOO_SERVER_PASSWORDS: flashex
    ports:
      - 2181:2181

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userDb
    ports:
      - 3306:3306